#!/bin/bash
#SBATCH --job-name="ssast-librispeech100"
#SBATCH --nodes=1
#SBATCH --gres=gpu:1
#SBATCH --exclude=damnii[07-12],landonia[01-08,21-25]
#SBATCH --cpus-per-task=4
#SBATCH --mem=24G
#SBATCH --output=./slurm_log/log_%j.txt

set -x
# Load environment (Modify these paths as needed for your specific cluster setup)
# . /data/sls/scratch/share-201907/slstoolchainrc
. /home/htang2/toolchain-20251006/toolchain.rc
source ../../../venvssast/bin/activate
export TORCH_HOME=../../pretrained_models
mkdir -p ./exp
mkdir -p ./slurm_log

# --- CONFIGURATION ---
# Path to the zipped dataset provided in the prompt
SOURCE_TAR=~/ssast/src/prep_data/librispeech/train-clean-100.tar.gz

# Scratch directory setup
SCRATCH_ROOT="/disk/scratch/${USER}/librispeech100"

echo "Source: $SOURCE_TAR"
echo "Scratch Target: $SCRATCH_ROOT"

# --- DATA PREPARATION ---

# 1. Unzip Data if not present
if [ -d "$SCRATCH_ROOT/LibriSpeech" ]; then
    echo "Data directory $SCRATCH_ROOT/LibriSpeech already exists. Skipping unzip."
else
    echo "Unzipping dataset to Scratch..."
    mkdir -p $SCRATCH_ROOT
    if [ -f "$SOURCE_TAR" ]; then
        # Unzip into SCRATCH_ROOT. This usually creates a 'LibriSpeech' folder inside.
        tar -xzf "$SOURCE_TAR" -C "$SCRATCH_ROOT"
        echo "Unzip complete."
    else
        echo "Error: Source file $SOURCE_TAR not found!"
        exit 1
    fi
fi

# 2. Run Python Prep Script
echo "Generating JSON files and Label CSV..."
# Pass the full path to the LibriSpeech folder inside scratch
python prep_ls.py --dataset_path "$SCRATCH_ROOT/LibriSpeech"

# --- MODEL TRAINING ---

pretrain_exp=./../../pretrain/exp/
# Provide the pretrained model name as the first argument to this script, 
# or default to a standard one if not provided.
pretrain_model="${1:-mask01-tiny-f16-t16-b64-lr5e-4-m400-pretrain_mpmhb-librispeech360}"
pretrain_path=./${pretrain_exp}/${pretrain_model}/models/best_audio_model.pth

# If specific model path not found, try to download or handle gracefully
if [ ! -f "$pretrain_path" ]; then
    echo "Warning: Pretrained model not found at $pretrain_path"
    echo "Ensure you have the correct path or download a pretrained model."
    # Optional: Logic to download a default model if needed
fi

dataset=librispeech
# Standard Normalization stats for Librispeech
dataset_mean=-4.2677393
dataset_std=4.5689974

target_length=1024  # Librispeech clips are longer, usually ~10s (1024 frames)
noise=False         # Usually False for Clean Speech tasks

# Paths generated by prep_ls.py
tr_data=./data/datafiles/librispeech_train_data.json
val_data=./data/datafiles/librispeech_validation_data.json
eval_data=./data/datafiles/librispeech_eval_data.json
label_csv=./data/datafiles/vocab.json

# Hyperparameters
bal=none
lr=1e-4             # Slightly lower LR for fine-tuning on larger model
freqm=48
timem=48
mixup=0.5
epoch=30
batch_size=24       # Reduced batch size as target_length 1024 consumes more VRAM
fshape=16
tshape=16
fstride=10          # Overlap for fine-tuning
tstride=10

task=ft_asr         # Fine-tuning for ASR task
model_size="${2:-tiny}" # Default to tiny model
head_lr=10          # Higher learning rate for the new classification head

# N_CLASS is calculated based on train-clean-100 speakers (approx 251)
# You can grep the csv to get exact line count minus header
n_class=$(python -c "import json; print(len(json.load(open('$label_csv'))))")
echo "Detected $n_class classes (vocab size)."

exp_dir=./exp/test-ls100-f$fstride-t$tstride-b$batch_size-lr${lr}-${task}-${model_size}-noise${noise}

echo "Starting Training..."

CUDA_CACHE_DISABLE=1 python -W ignore ../../run.py --dataset ${dataset} \
--data-train ${tr_data} --data-val ${val_data} --data-eval ${eval_data} --exp-dir $exp_dir \
--label-csv ${label_csv} --n_class ${n_class} \
--lr $lr --n-epochs ${epoch} --batch-size $batch_size --save_model True \
--freqm $freqm --timem $timem --mixup ${mixup} --bal ${bal} \
--tstride $tstride --fstride $fstride --fshape ${fshape} --tshape ${tshape} --warmup True --task ${task} \
--model_size ${model_size} --adaptschedule True \
--pretrained_mdl_path ${pretrain_path} \
--dataset_mean ${dataset_mean} --dataset_std ${dataset_std} --target_length ${target_length} \
--num_mel_bins 128 --head_lr ${head_lr} --noise ${noise} \
--lrscheduler_start 5 --lrscheduler_step 1 --lrscheduler_decay 0.85 --wa False \
--loss CTC --metrics wer